### ISSUE TITLE
cannot locate cursor correctly

### ISSUE THREAD

**Issue by sibosutd** [JJack27/activate-power-mode#1]
It seems like the plugin cannot locate the cursor correctly after toggling soft wrap. It somehow misses the lines with soft wrap. I am using Ubuntu 14.04

**Comment by JJack27** [comment]
Thank you for inform me this issue. However, I would like to suggest you to contact the original author as I mentioned the in README file. Due to my coding experience as a first year university student, I cannot solve this problem at a short time. But I will try to solve it after I formally learn the script programming language. If you find a way of solving this problem, please contact me :) I would like to now how that works.

**Comment by sibosutd** [comment]
Yes, thanks for your reply. 
I also found that I posted it to a wrong place. I just reported this issue to the original author already.
